### ISSUE TITLE
Refaktorer addSkosConcept

### ISSUE THREAD

**Issue by matsjs** [Informasjonsforvaltning/dataset-catalog#18]
addSkosConcept i datasett-catalog ser ikke ut. Denne bør skrives om til en mer (og bedre) generell kode.

Noen av feltene som blir satt til SkosConcept skal være det. Handlingsplan:
- [X] Opprett liste av alle feltene som blir satt til SkosConcept i dataset-catalog:

**Datasett:**
dcatno:legalBasisFor*
dct:conformsTo
dcatno:informationModel

**Datasett -> Distribution:**
dct:license
dct:conformsTo
foaf:page

**Datasett -> Distribution -> DataDistributionService:**
dcat:endpointDescription

- [x] Gå gjennom listen for å filtrere ut de som blir feilsatt til SkosConcept
- [x] Fjern eventuelle avhengigheter til SkosConcept i portal for disse feltene
- [x] Fjern avhengigheter til SkosConcept for feltene i fdk-rdf-parser
- [x] Refaktorer feltene i dataset-catalog

**Comment by NilsOveTen** [comment]
Tilstand atm er:
Datasett:
 - dcatno:legalBasisFor*: Løst ved overgang til dcat-ap-no v2
 - dct:conformsTo: Usikkert
 - dcatno:informationModel: Løst ved overgang til dcat-ap-no v2

Datasett -> Distribution:
 - dct:license: Skal endres til lenke. https://github.com/Informasjonsforvaltning/dataset-catalog/issues/77
 - dct:conformsTo: Usikkert
 - foaf:page: Skal endres til lenke. https://github.com/Informasjonsforvaltning/dataset-catalog/issues/77

Datasett -> Distribution -> DataDistributionService:
 - dcat:endpointDescription: Skal være lenke til openAPI-spec. Krever endring av parse fra dataservice-catalogue og medførende ETL. https://github.com/Informasjonsforvaltning/dataset-catalog/issues/78
