### ISSUE TITLE
Søkefunksjonalitet etter tittel i liste over datasett

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/dataset-catalog#37]
Hentet fra behov:
https://github.com/Informasjonsforvaltning/behov/issues/519

Se design:
https://eggedosis.github.io/fdk-design/redirects/register/dataset/skatteetaten-2-catalog.html

forbeholdt at vi benytter mongoDB api'et (spring standarder?):

NB! Denne funksjonaliteten skal implementeres uavhengig hvilken bruker som logger seg på.

- [x] Backend støtte for søkefunksjon mot datasettbeskrivelser som er for innlogget virksomhet

- [x] Visning av søkefunksjonalitet

- [x] Oppdatering av resultatliste

- [ ] Denne bør lages som en komponent i komponent-biblioteket og implementeres i concept-catalog-gui også.

Som: bruker/forvalter av Skatteetatens lokale datasettkatalog
Ønsker jeg å: ha en søkefunksjon der jeg kan søke på ord i titler/beskrivelser på datasettene
Slik at: jeg lettere kan finne sett jeg lurer på om vi har beskrevet, evt om det er datasett med liknende innhold

**Comment by shenluna** [comment]
Verifisert i Staging
