### ISSUE TITLE
Fjern bruk av `http://difi.no/dcatno#`

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/dataset-catalog#65]
- [x] accessRightsComment -> Skal ifølge dcat-ap-no v2.0 være cpsv:follows
- [x] objective -> Kan flyttes inn som en del av description (ref kommentar)
- [x] legalBasisForProcessing
- [x] legalBasisForRestriction
- [x] legalBasisForAccess
- [x] informationModel

**Comment by stigbd** [comment]
Re `dcatno:objective`:
Vi skal fjerne bruken av dcatno:objective. 

Framgangsmåte:
1. Der beskrivelse ikkje fins frå før, legg verdien i `dcatno:objective` inn i `dct:description`, 
2. Der beskrivelse fins frå før, legg verdien i dcatno:objective inn som siste avsnitt i `dct:description`.

**Comment by stigbd** [comment]
Re `dcatno:objective`:
Vi skal fjerne bruken av dcatno:objective. 

Framgangsmåte:
1. Der beskrivelse ikkje fins frå før, legg verdien i `dcatno:objective` inn i `dct:description`, 
2. Der beskrivelse fins frå før, legg verdien i dcatno:objective inn som siste avsnitt i `dct:description`.

**Comment by stigbd** [comment]
Merk at `dcatno:accessRightsComment` er gyldig dcat-ap-no v1.1.
https://data.norge.no/specification/dcat-ap-no/v1.1/#datasett-skjermingshjemmel

**Comment by stigbd** [comment]
Og før vi faktisk fjerner desse, bør vi ta ein gjennomgang med @joebrreg og @jimjyang

**Comment by jimjyang** [comment]
informationModel -> dct:conformsTo (som refererer til en informasjonsmodell som i ModellDCAT-AP-NO er en subklasse av dct:Standard)

**Comment by jimjyang** [comment]
legalBasisForProcessing, legalBasisForRestriction og legalBasisForAccess: kort fortalt to steg: 
1. bruk `cpsv:follows` som peker til en `cpsv:Rule`. Ved å bruke `dct:type` i `cpsv:Rule` kan man spesifisere om regelen er `cpsvno:ruleForDisclosure` (tilsvarende legalBasisForAccess) eller `cpsvno:ruleForNonDisclosure` (tilsvarende legalBasisForRestriction). NB! Mangler nå en predefinert `dct:type` som tilsvarer legalBasisForProcessing (f.eks. `cpsvno:legalBasisForProcessing`).
2. fra `cpsv:Rule` og via `eli:LegalResource` lenkes det til selve kilden (lov/forskrift/o.l.), ved å bruke `xsd:seeAlso`.  

Se [eksemplet for bruk av cpsv:follows i DCAT-AP-NO](https://data.norge.no/specification/dcat-ap-no/#Datasett-f%C3%B8lger).

**Comment by stigbd** [comment]
Eksemplene:
```
:aDataset
   a dcat:Dataset ;
   cpsv:follows :aNonDisclosureRule, :aDisclosureRule .

:aNonDisclosureRule
   a cpsv:Rule ;
   dct:type cpsvno:ruleForNonDisclosure ;
   dct:description "skjerminghjemmel"@nb , "legal basis for non-disclosure"@en .

:aDisclosureRule
   a cpsv:Rule ;
   dct:type cpsvno:ruleForDisclosure ;
   dct:description "utleveringshjemmel"@nb , "legal basis for disclosure"@en ;
   cpsv:implements :aLegalResource .

:aLegalResource
   a eli:LegalResouce ;
   dct:description "Eksempelregelverk"@nb , "Example legal resource"@en ;
   xsd:seeAlso <https:/example.com/eli/lov/2020/01/01/section/1> .
```

**Comment by stigbd** [comment]
I dag ser disse slik ut:
```
dcatno:legalBasisForAccess [ a skos:Concept , dcterms:RightsStatement ;
dcterms:source "https://lovdata.no/NL/lov/2016-05-27-14/§3-3" ;
skos:prefLabel "Skatteforvaltningsloven §§ 3-3 til 3-9"@nb
] ;
dcatno:legalBasisForProcessing [ a skos:Concept , dcterms:RightsStatement ;
dcterms:source "https://lovdata.no/NL/lov/2016-05-27-14/§7-9" ;
skos:prefLabel "Skatteforvaltningsloven §7-9 (2)"@nb
] ;
dcatno:legalBasisForProcessing [ a skos:Concept , dcterms:RightsStatement ;
dcterms:source "https://lovdata.no/NL/lov/2016-05-27-14/§7-13" ;
skos:prefLabel "Skatteforvaltningsloven §7-13"@nb
] ;
dcatno:legalBasisForProcessing [ a skos:Concept , dcterms:RightsStatement ;
dcterms:source "https://lovdata.no/pro/SF/forskrift/2016-11-23-1360/KAPITTEL_5-7-2" ;
skos:prefLabel "Skatteforvaltningsforskriften §7-9, B"@nb
] ;
```

**Comment by NilsOveTen** [comment]
```
dcatno:legalBasisForRestriction
                [ a               skos:Concept , dcterms:RightsStatement ;
                  dcterms:source  "https://lovdata.no/NL/lov/2016-05-27-14/§3-1" ;
                  skos:prefLabel  "Skatteforvaltningsloven §3-1"@nb
                ] ;
```

**Comment by jimjyang** [comment]
Med forbehold om skrive- og/eller klipp-og-lim-feil, her de "legal-tingene" konvertert til DCAT-AP-NO v.2: 
`````
@prefix cpsv: <http://purl.org/vocab/cpsv#> .
@prefix cpsvno: <https://data.norge.no/vocabulary/cpsvno#> .
@prefix dcat: <http://www.w3.org/ns/dcat#> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix eli: <http://data.europa.eu/eli/ontology#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<> a dcat:Dataset ;
    cpsv:follows [ a cpsv:Rule ; # erstatter dcatno:legalBasisForRestriction i DCAT-AP-NO v.1.1
          dcterms:type cpsvno:ruleForNonDisclosure ;
          cpsv:implements [ a eli:eli:LegalResouce ;
                xsd:seeAlso "https://lovdata.no/NL/lov/2016-05-27-14/§3-1" ;
                dcterms:title "Skatteforvaltningsloven §3-1"@nb ;
          ] ;
        ] , [ a cpsv:Rule ; # erstatter dcatno:legalBasisForAccess i DCAT-AP-NO v.1.1
            dcterms:type cpsvno:ruleForDisclosure ;
            cpsv:implements [ a eli:eli:LegalResouce ;
                  xsd:seeAlso "https://lovdata.no/NL/lov/2016-05-27-14/§3-3" ;
                  dcterms:title "Skatteforvaltningsloven §§ 3-3 til 3-9"@nb ;
            ] ;
          ] , [ a cpsv:Rule ; # tilsvarende dcatno:legalBasisForProcessing i DCAT-AP-NO v.1.1
              dcterms:type cpsvno:ruleForDataProcessing ; # NB! Denne har vi ikke ennå
              cpsv:implements [ a eli:eli:LegalResouce ;
                    xsd:seeAlso "https://lovdata.no/NL/lov/2016-05-27-14/§3-3" ;
                    dcterms:title "Skatteforvaltningsloven §§ 3-3 til 3-9"@nb ;
              ] ;
            ] ;
      .
`````

Som sagt mangler vi p.t. `cpsvno:ruleForDataProcessing`.

**Comment by jimjyang** [comment]
Nå er en ny regeltype `cpsvno:ruleForDataProcessing` inkludert i [cpsvno](https://data.norge.no/vocabulary/cpsvno).

**Comment by stigbd** [comment]
To spørsmål til @jimjyang :

1. Er det mulig å mappe  accessRightsComment (1.1) -> cpsv:follows (2.0)?
2. Viss ja, korleis skal vi utforme denne mappinga?

**Comment by jimjyang** [comment]
`dcatno:accessRightsComment` var i v.1.1 ment for å brukes til å referere til en skjermingshjemmel. Den skal derfor ha samme mapping som for `dcatno:legalBasisForRestriction` i v.1.1: 
````
<> a dcat:Dataset ;
    cpsv:follows [ a cpsv:Rule ; # erstatter dcatno:legalBasisForRestriction i DCAT-AP-NO v.1.1
          dcterms:type cpsvno:ruleForNonDisclosure ;
          cpsv:implements [ a eli:eli:LegalResouce ;
                xsd:seeAlso "https://lovdata.no/NL/lov/2016-05-27-14/§3-1" ;
                dcterms:title "Skatteforvaltningsloven §3-1"@nb .
````
