### ISSUE TITLE
Fjern bruk av namespace http://dcat.no/dcatapi/

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/dataset-catalog#67]
- [x] accessService -> Skal i følge dcat-ap-no v2.0 være dcat:accessService
- [x] endpointDescription -> Skal i følge dcat-ap-no v2.0 være dcat:endpointDescription
- [x] DataDistributionService -> dcat:accessService har i følge dcat-ap-no v2.0 range=dcat:DataService

**Comment by stigbd** [comment]
Mapping ser ok ut. Køyr!
