### ISSUE TITLE
Endre hasBody i dqv:hasQualityAnnotation til å følge dqv-ap-no

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/dataset-catalog#71]
Det som blir brukt nå, dvs prov:hasBody, er feil. Det skal [ifølge dqv-ap-no](https://data.norge.no/specification/dqv-ap-no/#Kvalitetsnote_harTekstdel) være oa:hasBody

**Comment by shenluna** [comment]
Testet OK
