### ISSUE TITLE
adms:sample peiker på "tom" Distribusjon

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/dataset-catalog#88]
I datasettet [Nasjonalt rutedatasett for kollektivtrafikk i Norge](https://data.transportportal.no/datasets/f8327e57-60fa-440f-9ecd-a8765ca13ae6) finner vi følgande triple:
       adms:sample                [ a  dcat:Distribution ] ;

Relevant del av spesifikasjonen er her https://data.norge.no/specification/dcat-ap-no/#Datasett-eksempeldata

Sjølv om dette er formelt korrekt, virkar det som ein feil å lage dette triplet, sidan adms:sample peikar på _ingenting_.

**Comment by jeffreiffers** [comment]
@joebrreg Fint om du kan verifisere at problemet er løst. Jeg har testet og det ser bra ut.
